from yacs.config import CfgNode as CN

def get_config():
    cfg = CN()
    MODELS = CN()

    MODELS.NAME = "Hourglass"
    HGNETS = CN()

    HGNETS.DEPTH = 4
    HGNETS.NUM_STACKS = 2
    HGNETS.NUM_BLOCKS = 1

    HGNETS.INPLANES = 64
    HGNETS.NUM_FEATS = 128

    MODELS.HGNETS = HGNETS
    MODELS.DEVICE = "cuda"
    MODELS.WEIGHTS = ""
    MODELS.HEAD_SIZE = [[3], [1], [1], [2], [2]]
    MODELS.OUT_FEATURE_CHANNELS = 256

    MODELS.LOSS_WEIGHTS = CN(new_allowed=True)

    PARSING_HEAD = CN()

    PARSING_HEAD.MAX_DISTANCE = 5.0

    PARSING_HEAD.N_STC_POSL = 300
    PARSING_HEAD.N_STC_NEGL = 40

    PARSING_HEAD.MATCHING_STRATEGY = 'junction'
    PARSING_HEAD.N_DYN_JUNC = 300
    PARSING_HEAD.N_DYN_POSL = 300
    PARSING_HEAD.N_DYN_NEGL = 300
    PARSING_HEAD.N_DYN_OTHR = 0
    PARSING_HEAD.N_DYN_OTHR2 = 300

    PARSING_HEAD.N_PTS0 = 32
    PARSING_HEAD.N_PTS1 = 8

    PARSING_HEAD.DIM_LOI = 128
    PARSING_HEAD.DIM_FC = 1024
    PARSING_HEAD.USE_RESIDUAL = True
    PARSING_HEAD.N_OUT_JUNC = 250
    PARSING_HEAD.N_OUT_LINE = 2500

    MODELS.PARSING_HEAD = PARSING_HEAD
    MODELS.SCALE = 1.0

    cfg.MODEL = MODELS

    return cfg
